### ISSUE TITLE
Could not mutate secret object

### ISSUE THREAD

**Issue by kirosvi** [bank-vaults/secrets-webhook#348]
### Preflight Checklist

- [x] I have searched the [issue tracker](https://www.github.com/bank-vaults/secrets-webhook/issues) for an issue that matches the one I want to file, without success.
- [x] I am not looking for support or already pursued the available [support channels](https://bank-vaults.dev/docs/support) without success.
- [x] I agree to follow the [Code of Conduct](https://bank-vaults.dev/docs/code-of-conduct).

### Secrets Webhook Version

v0.2.2

### Installation Type

Official Helm chart

### Kubernetes Version

v1.31.7-gke.1212000

### Kubernetes Distribution/Provisioner

GKE

### Expected Behavior

expecting a mutation of the secret object after creating it.

### Actual Behavior

Got en error 

```
level=ERROR msg="Admission review error: could not mutate object: mutate generic secret failed: key 'auth2\n' not found under path: k8s-stage/data/common/gar/regcred/reader" app=secrets-webhook svc=http.Handler op=create name=mysecret wh-version=v1beta1 path=/secrets webhook-kind=mutating kind=v1/Secret ns=app-migrate-secrets webhook-id=secrets-secret request-id=f4935d60-4139-4bb7-b43c-a1448bcf0bdf dry-run=false trace-id=""
```

### Steps To Reproduce

Create a base64 string with the path of the secret.
Add it to the secret manifest and apply it.
Get an error.

### Configuration

```yaml
vault version `Vault 1.18.1`

Secret that doesn't work

---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  annotations:
    secrets-webhook.security.bank-vaults.io/provider: vault
    secrets-webhook.security.bank-vaults.io/vault-addr: https://vault.example.com:443
    secrets-webhook.security.bank-vaults.io/vault-path: kubernetes-stage
    secrets-webhook.security.bank-vaults.io/vault-role: stage_vault_injector
    secrets-webhook.security.bank-vaults.io/vault-skip-verify: "true"
  labels:
    vault-injection: enabled
data:
  key1: dmF1bHQ6azhzLXN0YWdlL2RhdGEvY29tbW9uL2dhci9yZWdjcmVkL3JlYWRlciNhdXRoMgo=


ConfigMap with same path that work fine

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-configmap
  annotations:
    secrets-webhook.security.bank-vaults.io/provider: vault
    secrets-webhook.security.bank-vaults.io/vault-addr: https://vault.example.com:443
    secrets-webhook.security.bank-vaults.io/vault-path: kubernetes-stage
    secrets-webhook.security.bank-vaults.io/vault-role: stage_vault_injector
    secrets-webhook.security.bank-vaults.io/vault-skip-verify: "true"
  labels:
    vault-injection: enabled
data:
  test: vault:k8s-stage/data/common/gar/regcred/reader#auth2
```

### Logs

```shell
time=2025-05-13T05:35:53.002Z level=DEBUG msg="config.Role = 'stage_vault_injector'" app=secrets-webhook
time=2025-05-13T05:35:53.220Z level=INFO msg="received new Vault token" app=secrets-webhook path=kubernetes-stage addr="" role=stage_vault_injector
time=2025-05-13T05:35:53.220Z level=INFO msg="initial Vault token arrived" app=secrets-webhook
time=2025-05-13T05:35:53.229Z level=INFO msg="Vault token renewal closed" app=secrets-webhook
time=2025-05-13T05:35:53.230Z level=ERROR msg="Admission review request failed" app=secrets-webhook kind=v1/Secret ns=cpap-migrate-secrets webhook-id=secrets-secret request-id=f4935d60-4139-4bb7-b43c-a1448bcf0bdf dry-run=false trace-id="" op=create name=mysecret wh-version=v1beta1 path=/secrets webhook-kind=mutating error="key 'auth2\n' not found under path: k8s-stage/data/common/gar/regcred/reader\ngithub.com/bank-vaults/vault-sdk/injector/vault.(*SecretInjector).InjectSecretsFromVault\n\t/go/pkg/mod/github.com/bank-vaults/vault-sdk@v0.10.2/injector/vault/injector.go:325\ngithub.com/bank-vaults/vault-sdk/injector/vault.(*SecretInjector).GetDataFromVault\n\t/go/pkg/mod/github.com/bank-vaults/vault-sdk@v0.10.2/injector/vault/injector.go:471\ngithub.com/bank-vaults/secrets-webhook/pkg/provider/vault.mutateSecretData\n\t/usr/local/src/secrets-webhook/pkg/provider/vault/secret.go:120\ngithub.com/bank-vaults/secrets-webhook/pkg/provider/vault.(*mutator).MutateSecret\n\t/usr/local/src/secrets-webhook/pkg/provider/vault/secret.go:68\ngithub.com/bank-vaults/secrets-webhook/pkg/webhook.(*MutatingWebhook).SecretsMutator\n\t/usr/local/src/secrets-webhook/pkg/webhook/webhook.go:98\nmain.main.ErrorLoggerMutator.func6\n\t/usr/local/src/secrets-webhook/pkg/webhook/webhook.go:159\ngithub.com/slok/kubewebhook/v2/pkg/webhook/mutating.MutatorFunc.Mutate\n\t/go/pkg/mod/github.com/slok/kubewebhook/v2@v2.7.0/pkg/webhook/mutating/mutator.go:45\ngithub.com/slok/kubewebhook/v2/pkg/webhook/mutating.mutatingWebhook.mutatingAdmissionReview\n\t/go/pkg/mod/github.com/slok/kubewebhook/v2@v2.7.0/pkg/webhook/mutating/webhook.go:116\ngithub.com/slok/kubewebhook/v2/pkg/webhook/mutating.mutatingWebhook.Review\n\t/go/pkg/mod/github.com/slok/kubewebhook/v2@v2.7.0/pkg/webhook/mutating/webhook.go:104\ngithub.com/slok/kubewebhook/v2/pkg/webhook.measuredWebhook.Review\n\t/go/pkg/mod/github.com/slok/kubewebhook/v2@v2.7.0/pkg/webhook/metrics.go:113\ngithub.com/slok/kubewebhook/v2/pkg/http.handler.ServeHTTP\n\t/go/pkg/mod/github.com/slok/kubewebhook/v2@v2.7.0/pkg/http/handler.go:148\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2822\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:3301\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:2102\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1700\nmutate generic secret failed\ngithub.com/bank-vaults/secrets-webhook/pkg/provider/vault.(*mutator).MutateSecret\n\t/usr/local/src/secrets-webhook/pkg/provider/vault/secret.go:70\ngithub.com/bank-vaults/secrets-webhook/pkg/webhook.(*MutatingWebhook).SecretsMutator\n\t/usr/local/src/secrets-webhook/pkg/webhook/webhook.go:98\nmain.main.ErrorLoggerMutator.func6\n\t/usr/local/src/secrets-webhook/pkg/webhook/webhook.go:159\ngithub.com/slok/kubewebhook/v2/pkg/webhook/mutating.MutatorFunc.Mutate\n\t/go/pkg/mod/github.com/slok/kubewebhook/v2@v2.7.0/pkg/webhook/mutating/mutator.go:45\ngithub.com/slok/kubewebhook/v2/pkg/webhook/mutating.mutatingWebhook.mutatingAdmissionReview\n\t/go/pkg/mod/github.com/slok/kubewebhook/v2@v2.7.0/pkg/webhook/mutating/webhook.go:116\ngithub.com/slok/kubewebhook/v2/pkg/webhook/mutating.mutatingWebhook.Review\n\t/go/pkg/mod/github.com/slok/kubewebhook/v2@v2.7.0/pkg/webhook/mutating/webhook.go:104\ngithub.com/slok/kubewebhook/v2/pkg/webhook.measuredWebhook.Review\n\t/go/pkg/mod/github.com/slok/kubewebhook/v2@v2.7.0/pkg/webhook/metrics.go:113\ngithub.com/slok/kubewebhook/v2/pkg/http.handler.ServeHTTP\n\t/go/pkg/mod/github.com/slok/kubewebhook/v2@v2.7.0/pkg/http/handler.go:148\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2822\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:3301\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:2102\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1700"
time=2025-05-13T05:35:53.230Z level=ERROR msg="Admission review error: could not mutate object: mutate generic secret failed: key 'auth2\n' not found under path: k8s-stage/data/common/gar/regcred/reader" app=secrets-webhook svc=http.Handler op=create name=mysecret wh-version=v1beta1 path=/secrets webhook-kind=mutating kind=v1/Secret ns=cpap-migrate-secrets webhook-id=secrets-secret request-id=f4935d60-4139-4bb7-b43c-a1448bcf0bdf dry-run=false trace-id=""
```

### Additional Information

We had an issue with the old app vault-webhook-secrets for injecting dockerconfigjson. After a small chat in [Slack](https://cloud-native.slack.com/archives/C078PHYK38W/p1747031195789579) channel, we have migrated to this webhook, but faced an issue with mutating secrets, also. I've tried different paths, secrets, and different k8s clusters, but always the same error.
